1.1 Continued writing some tests for existing code - Removed the obselete paginatable collectoin - Encountered strange 'PersistentFactoryNameResolver.resolveFactory is not a function' TypeError   in Karma - Stripped down some of the Karma dependencies so that we can use the newest version of Jasmine